#bin/bash
#
#	----------------------------------------------------------------------------
#	ANSI escape/color codes include file for game-server mangement scripts
#	============================================================================
#	Created:       2024-05-19, by Weasel.SteamID.155@gMail.com        
#	Last modified: 2024-05-27, by Weasel.SteamID.155@gMail.com
#	----------------------------------------------------------------------------
#
#	USAGE NOTES:
#
#	Includes stuff such as ...
#	
#		ANSI color escape codes.
#
#	----------------------------------------------------------------------------
#
#	Define some stuff ...
#
#		Define some ANSI color escape sequences ...
#
ANSI_OFF="\033[0m";
ANSI_BLACK="\033[0;30m";
ANSI_RED="\033[0;31m";
ANSI_GREEN="\033[0;32m";
ANSI_BROWN="\033[0;33m";
ANSI_BLUE="\033[0;34m";
ANSI_PURPLE="\033[0;35m";
ANSI_CYAN="\033[0;36m";
ANSI_GRAYLT="\033[0;37m";
ANSI_GRAYDK="\033[1;30m";
ANSI_REDLT="\033[1;31m";
ANSI_GREENLT="\033[1;32m";
ANSI_YELLOW="\033[1;33m";
ANSI_BLUELT="\033[1;34m";
ANSI_PURPLELT="\033[1;35m";
ANSI_CYANLT="\033[1;36m";
ANSI_WHITE="\033[1;37m"
#
#	... thats all folks!
#
